/*
*	Generated by Tyson Lawrie on 2015-03-05.
*	Based on documentation by Fiberlink
*	
*	Plugin: MaaS360 Utilities
*	Filename: CustomerType.java
 */

package com.mobilefirst.fiberlink;

public enum CustomerType {
	NORMAL,
	SPS,
	MAM,
}
